import * as THREE from 'three'
import { useGLTF, Sparkles, Line, useAnimations } from '@react-three/drei'
import { useControls } from 'leva'
import { Suspense, useEffect, useState, useRef } from 'react'

const glowRed = new THREE.MeshBasicMaterial({ color: new THREE.Color(7, 0, 0.5), toneMapped: false })
const glowBlue = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 0.5, 20), toneMapped: false })
const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 3, 1), toneMapped: false })

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://discourse.threejs.org/t/struggling-with-gltf-and-lighting/39564
*/
export function Fire({ ...props }) {
  // const { p1 } = useControls('F Pos', {
  //   p1: {
  //     value: { x: 0, y: 0, z: 0 },
  //     step: 0.01,
  //     joystick: 'invertY',
  //   },
  // })

  const fireRef = useRef()

  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/campfire-transformed.glb')
  const { actions } = useAnimations(animations, group)
  const halo = 0.15

  useEffect(() => {
    if (actions) {
      // Loop through all available animation actions and play them
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset().setLoop(THREE.LoopRepeat).play()
        }
      })
    }
  }, [actions])

  return (
    <group {...props} dispose={null} position={[0.21, 2.58, -0.56]} scale={halo} ref={group}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="fire_part_00_3" position={[-0.106, -0.255, -0.101]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} material={glowRed}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} />
          </group>
          <group name="fire_part_01_4" position={[0.032, 0.363, 0.018]} rotation={[Math.PI / 2, 0, 0.265]} scale={0}>
            <mesh material={glowRed} name="Object_8" geometry={nodes.Object_8.geometry} />
          </group>
          <group name="fire_part_02_5" position={[-0.083, -0.616, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_10" geometry={nodes.Object_10.geometry} />
          </group>
          <group name="fire_part_03_6" material={glowRed} position={[-0.016, 1.579, 0.012]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} />
          </group>
          <group name="fire_part_04_7" position={[0.244, -0.588, -0.304]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
            <mesh material={glowRed} name="Object_14" geometry={nodes.Object_14.geometry} />
          </group>
          <group name="fire_part_05_8" rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_16" geometry={nodes.Object_16.geometry} />
          </group>
          <group name="fire_part_06_9" position={[0.096, -0.413, 0.031]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_18" geometry={nodes.Object_18.geometry} />
          </group>
          <group name="fire_part_07_10" position={[-0.421, -1.981, 0.142]} rotation={[1.978, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_20" geometry={nodes.Object_20.geometry} />
          </group>
          <group name="fire_part_08_11" position={[0.167, -0.7, -0.216]} rotation={[Math.PI / 2, 0.499, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_22" geometry={nodes.Object_22.geometry} />
          </group>
          <group name="fire_part_09_12" position={[0.502, -1.262, 0.212]} rotation={[0.917, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_24" geometry={nodes.Object_24.geometry} />
          </group>
          <group name="fire_part_010_13" position={[-0.098, -0.556, 0.162]} rotation={[Math.PI / 2, -0.515, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_26" geometry={nodes.Object_26.geometry} />
          </group>
          <group name="fire_part_011_14" position={[0.683, 0.232, 0.474]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_28" geometry={nodes.Object_28.geometry} />
          </group>
          <group name="fire_part_012_15" position={[0.591, 0.888, -0.734]} rotation={[1.594, 0.143, -0.042]} scale={0.027}>
            <mesh material={glowRed} name="Object_30" geometry={nodes.Object_30.geometry} />
          </group>
          <group name="fire_part_013_16" position={[-0.801, 0.124, 0.324]} rotation={[1.802, 0.14, -0.075]} scale={0.04}>
            <mesh material={glowRed} name="Object_32" geometry={nodes.Object_32.geometry} />
          </group>
          <group name="fire_part_014_17" position={[0.089, -1.514, -0.212]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_34" geometry={nodes.Object_34.geometry} />
          </group>
          <group name="fire_part_015_18" position={[0.181, -0.553, -0.256]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_36" geometry={nodes.Object_36.geometry} />
          </group>
          <group name="fire_part_016_19" position={[0.001, -1.02, -0.016]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
            <mesh material={glowRed} name="Object_38" geometry={nodes.Object_38.geometry} />
          </group>
          <group name="fire_part_017_20" position={[-0.116, -1.159, 0.541]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
            <mesh material={glowRed} name="Object_40" geometry={nodes.Object_40.geometry} />
          </group>
          <group name="fire_part_018_21" position={[-0.211, -1.093, -0.611]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0.04, 0.04]}>
            <mesh material={glowRed} name="Object_42" geometry={nodes.Object_42.geometry} />
          </group>
          <group name="fire_part_019_22" position={[0.265, -0.932, 0.044]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
            <mesh material={glowRed} name="Object_44" geometry={nodes.Object_44.geometry} />
          </group>
          <group name="fire_part_020_23" position={[-0.003, -0.987, -0.186]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_46" geometry={nodes.Object_46.geometry} />
          </group>
          <group name="fire_part_021_24" position={[-0.249, -0.363, 0.031]} rotation={[Math.PI / 2, 0, 0]} scale={0.12}>
            <mesh material={glowRed} name="Object_48" geometry={nodes.Object_48.geometry} />
          </group>
          <group name="fire_part_022_25" position={[0.169, -0.28, -0.358]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_50" geometry={nodes.Object_50.geometry} />
          </group>
          <group name="fire_part_023_26" position={[0.495, -0.277, 0.145]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
            <mesh material={glowRed} name="Object_52" geometry={nodes.Object_52.geometry} />
          </group>
          <group name="fire_part_024_27" position={[0.495, -0.453, 0.145]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_54" geometry={nodes.Object_54.geometry} />
          </group>
          <group name="fire_part_025_28" position={[-0.116, 0.046, 0.541]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_56" geometry={nodes.Object_56.geometry} />
          </group>
          <group name="fire_part_026_29" position={[0.089, -1.084, -0.212]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_58" geometry={nodes.Object_58.geometry} />
          </group>
          <group name="fire_part_027_30" position={[0.089, -0.66, -0.212]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_60" geometry={nodes.Object_60.geometry} />
          </group>
          <group name="fire_part_028_31" position={[-0.008, -1.697, -0.076]} rotation={[Math.PI / 2, 0, 0]} scale={0.04}>
            <mesh material={glowRed} name="Object_62" geometry={nodes.Object_62.geometry} />
          </group>
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Campfire_MAT} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      </group>
    </group>
  )
}
