import * as THREE from 'three'
import { useGLTF, Sparkles, Line, Cloud, Clouds } from '@react-three/drei'
import { useControls } from 'leva'

const glowRed = new THREE.MeshBasicMaterial({ color: new THREE.Color(7, 0, 0.5), toneMapped: false })
const glowBlue = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 0.5, 20), toneMapped: false })
const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 3, 1), toneMapped: false })

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://discourse.threejs.org/t/struggling-with-gltf-and-lighting/39564
*/
export function Fog({ ...props }) {
  // const { p1 } = useControls('gdf', {
  //   p1: {
  //     value: { x: 0, y: 0, z: 0 },
  //     step: 0.01,
  //     joystick: 'invertY',
  //   },
  // })

  return (
    <group>
      {' '}
      <group scale={[0.5, 0.5, 5]}>
        <Cloud position={[0, -5, 2]} speed={0.2} opacity={1} />
        <Cloud position={[0, -5, -2]} speed={0.2} opacity={1} />

        <Cloud position={[12, -5, 0]} speed={0.2} opacity={1} />

        <Cloud position={[-12, -5, 0]} speed={0.2} opacity={1} />
      </group>
    </group>
  )
}
