import * as THREE from 'three'
import { useGLTF, Sparkles, Line } from '@react-three/drei'
import { useControls } from 'leva'

const glowRed = new THREE.MeshBasicMaterial({ color: new THREE.Color(7, 0, 0.5), toneMapped: false })
const glowBlue = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 0.5, 20), toneMapped: false })
const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 3, 1), toneMapped: false })

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://discourse.threejs.org/t/struggling-with-gltf-and-lighting/39564
*/
export function Mountain({ ...props }) {
  // const { position1 } = useControls('Mountain Pos', {
  //   p1: {
  //     value: { x: 0, y: 0, z: 0 },
  //     step: 0.01,
  //     joystick: 'invertY',
  //   },
  // })
  const { nodes, materials } = useGLTF('/mountain.glb')

  const halo = 5

  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]} position={[0, 0, 0]}>
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.defaultMat} scale={[halo, halo, halo]} />
    </group>
  )
}
