import * as THREE from 'three'
import { useGLTF, Sparkles, Line } from '@react-three/drei'
import { useControls } from 'leva'

const glowRed = new THREE.MeshBasicMaterial({ color: new THREE.Color(7, 0, 0.5), toneMapped: false })
const glowBlue = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 0.5, 20), toneMapped: false })
const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 3, 1), toneMapped: false })

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://discourse.threejs.org/t/struggling-with-gltf-and-lighting/39564
*/
export function Rope({ ...props }) {
  const curvePointsArray = [
    new THREE.Vector3(0.07, 2.74, -0.59),
    new THREE.Vector3(-0.06, 2.76, -0.59),
    new THREE.Vector3(-0.15, 2.775, -0.53),
    new THREE.Vector3(-0.52, 2.65, -0.53),
    new THREE.Vector3(-0.9, 2.25, -0.53),
    new THREE.Vector3(-1.2, 1.75, -0.55),
    new THREE.Vector3(-1.3, 1.44, -0.63),
    new THREE.Vector3(-2.39, -0.51, -1.28),
    new THREE.Vector3(-2.52, -0.71, -1.33),
    new THREE.Vector3(-2.71, -0.84, -1.35),
    new THREE.Vector3(-3, -0.96, -1.53),
    new THREE.Vector3(-3, -1, -1.53),

    new THREE.Vector3(-3.31, -1.17, -1.82),
    new THREE.Vector3(-3.51, -1.16, -2.07),
    new THREE.Vector3(-3.89, -1.16, -2.3),
    new THREE.Vector3(-4.54, -1.5, -2.71),
    new THREE.Vector3(-4.54, -1.8, -2.71),
  ]

  const curve = new THREE.CatmullRomCurve3(curvePointsArray)

  const curvePoints = curve.getPoints(50)
  const curveGeometry = new THREE.BufferGeometry().setFromPoints(curvePoints)
  // const { p1 } = useControls('Mountain Pos', {
  //   p1: {
  //     value: { x: 0, y: 0, z: 0 },
  //     step: 0.01,
  //     joystick: 'invertY',
  //   },
  // })

  return (
    <group>
      <Sparkles count={200} scale={[20, 20, 10]} size={1.5} speed={2} />

      {/* Sphere geometry */}
      <mesh position={[0, 0, 0]}>
        <sphereGeometry args={[0.02, 32, 32]} />
        <meshBasicMaterial color="yellow" />
      </mesh>
      <line geometry={curveGeometry} material={glowBlue} />
    </group>
  )
}
